export const mainContrast = '#00C2FF';
export const mainContrastWithoutOpacity = '#00C2FF';
export const titleText = '#f5f5f5';
export const selectBackground = '#919191'
export const contentText = "#212121";
export const white = '#ffffff';
export const black = '#000000';
export const doneBgColor = '#DADED9';
export const currentBgColor = '#26DA22';
export const futureBgColor = '#FF8F3F';
export const startColor = { h: 194, s: 100, l: 50 };
export const stopColor = { h: 115, s: 85, l: 35 };
